#!/usr/bin/env python3
"""Regenerate the embedded converter architecture matrix from pinned llama.cpp.

This is a maintainer tool, not a runtime dependency. The generated Go source is
committed so building or running salmon-model does not require Python.
"""
from __future__ import annotations

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "lib" / "llama.cpp" / "convert_hf_to_gguf.py"
OUTPUT = ROOT / "tools" / "salmon-model" / "internal" / "compat" / "architectures_generated.go"
COMMIT = "bf78f5439ee8e82e367674043303ebf8e92b4805"

tree = ast.parse(SOURCE.read_text(encoding="utf-8"))
classes = {
    node.name: [base.id for base in node.bases if isinstance(base, ast.Name)]
    for node in tree.body if isinstance(node, ast.ClassDef)
}

def derives(class_name: str, target: str) -> bool:
    pending, seen = [class_name], set()
    while pending:
        current = pending.pop()
        if current == target:
            return True
        if current in seen:
            continue
        seen.add(current)
        pending.extend(classes.get(current, []))
    return False

entries: dict[str, tuple[bool, bool]] = {}
for node in tree.body:
    if not isinstance(node, ast.ClassDef):
        continue
    for decorator in node.decorator_list:
        if not (isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Attribute) and decorator.func.attr == "register"):
            continue
        for argument in decorator.args:
            if not (isinstance(argument, ast.Constant) and isinstance(argument.value, str)):
                continue
            text, projector = entries.get(argument.value, (False, False))
            entries[argument.value] = (
                text or derives(node.name, "TextModel"),
                projector or derives(node.name, "MmprojModel"),
            )

lines = [
    "// Code generated by scripts/generate_converter_matrix.py; DO NOT EDIT.",
    "package compat", "", f'const ConverterLlamaCommit = "{COMMIT}"', "",
    "var converterArchitectures = map[string]ConverterCapability{",
]
for name, (text, projector) in sorted(entries.items()):
    lines.append(f'\t"{name}": {{Text: {str(text).lower()}, Projector: {str(projector).lower()}}},')
lines.extend(["}", ""])
OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"wrote {len(entries)} architectures to {OUTPUT}")
