name: Release Salmon Addon

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Prepare addons folder
        run: |
          mkdir -p addons/salmon/bin
          # Copy binaries if they exist
          cp salmon/bin/*.dll addons/salmon/bin/ 2>/dev/null || true
          cp salmon/bin/*.a addons/salmon/bin/ 2>/dev/null || true
          # Copy required extension and scripts
          cp salmon/salmon.gdextension addons/salmon/ 2>/dev/null || true
          cp salmon/model_download.bat addons/salmon/ 2>/dev/null || true
          cp salmon/model_download.sh addons/salmon/ 2>/dev/null || true
          # Copy license & readme to the addon root
          cp LICENSE addons/salmon/ 2>/dev/null || true
          cp README.md addons/salmon/ 2>/dev/null || true

      - name: Zip into correct structure
        run: |
          zip -r salmon-addon.zip addons LICENSE README.md

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: salmon-addon.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
